name: SWAN-CI

on:
  push:
    paths:
      - docker/**
      - .github/**
    branches:
      - "main"
      - "docker"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build the dockers
        run: DOCKER_BUILDKIT=1 docker compose -f docker/compose.yaml build
      # -
      #   name: Test swan
      #   run: DOCKER_BUILDKIT=1 docker compose -f docker/compose.yaml run swantest
      # -
      #   name: Push the dockers
      #   run: docker compose -f docker/compose.yaml push
